'use client'
import { useState } from 'react'
import Link from 'next/link'
import { BookOpen, Send } from 'lucide-react'
import { aiMutation, useAiLifecycle, useAiPrompts } from '@/features/ai/hooks/useAiAdmin'
import { AiHeader, Badge, Card, Loading, SectionTitle } from '@/features/ai/components/AiUi'

const envs = [['development', 'DEV'], ['test', 'TEST'], ['production', 'PROD']] as const
export default function BehaviorPage() {
  const prompts = useAiPrompts()
  const prompt: any = (Array.isArray(prompts.data) ? prompts.data : prompts.data?.items || []).find((p: any) => p.key === 'personality') || (Array.isArray(prompts.data) ? prompts.data[0] : undefined)
  const lifecycle = useAiLifecycle(prompt?.id)
  const [text, setText] = useState(''); const [notice, setNotice] = useState('')
  const save = async (publish = false) => { if (!prompt?.id) return; try { const v: any = await aiMutation(`/ai/admin/prompts/${prompt.id}/versions`, 'POST', { content: text }); if (publish && v?.id) await aiMutation(`/ai/admin/prompt-versions/${v.id}/publish`, 'POST'); setNotice(publish ? 'Personality publicada. Ahora requiere deployment.' : 'Draft guardado.'); lifecycle.versions.refresh() } catch (e: any) { setNotice(e.message) } }
  const draft = lifecycle.draft; const published = lifecycle.published
  return <div className="space-y-6"><AiHeader eyebrow="Behavior" title="Give Finnic a point of view." description="Shape the voice without touching the live version. Publishing is separate from deployment."><div className="flex flex-wrap gap-2"><Badge tone="navy">Draft · v{draft?.version || '—'}</Badge><Badge tone="teal">Published · v{published?.version || '—'}</Badge></div></AiHeader><Card>{lifecycle.versions.loading ? <Loading /> : <><SectionTitle icon={BookOpen} title="Personality editor" note="A published version only affects Finnic after deployment." />{notice && <p className="mb-4 rounded-xl bg-[#F6F2EC] p-3 text-sm text-[#8A7048]">{notice}</p>}<textarea value={text || draft?.content || ''} onChange={e => setText(e.target.value)} rows={14} className="w-full resize-y rounded-2xl border border-[#DDD9D4] bg-[#F5F2EE] p-4 text-sm leading-6 text-[#102D38] outline-none focus:border-[#407E8C]" placeholder="Describe how Finnic should speak, think and help…" /><div className="mt-4 flex flex-wrap gap-3"><button onClick={() => save(false)} className="rounded-full bg-[#E2EBEF] px-5 py-3 text-sm font-bold text-[#083A4F]">Save draft</button><button onClick={() => save(true)} className="inline-flex items-center gap-2 rounded-full bg-[#083A4F] px-5 py-3 text-sm font-bold text-white"><Send size={15} />Publish version</button></div></>}</Card><Card><SectionTitle icon={BookOpen} title="Deployment status" note="The resolver uses the active deployment, not the latest published version." /><div className="grid gap-2 sm:grid-cols-3">{envs.map(([env, label]) => { const active = lifecycle.activeByEnv[env]; return <div key={env} className="rounded-2xl bg-[#F5F2EE] p-4"><p className="text-[11px] font-bold tracking-widest text-[#607078]">{label}</p><p className="mt-2 text-sm font-semibold text-[#083A4F]">{active ? `Active · v${active.version}` : 'No deployment'}</p></div> })}</div>{published && envs.some(([env]) => !lifecycle.activeByEnv[env]) && <div className="mt-4 flex flex-col gap-3 rounded-2xl border border-[#E5D8C4] bg-[#FBF7F0] p-4 text-sm text-[#6D5739] sm:flex-row sm:items-center sm:justify-between"><span>Requiere deployment en DEV/TEST/PROD para afectar Finnic.</span><Link href="/ai/versions" className="font-bold underline underline-offset-4">Ir a Versions</Link></div>}</Card></div>
}
