import { CalendarClock, CreditCard } from 'lucide-react'
import type { BalanceProps } from '../types'
import { accountType, money, totalsFromSnapshot } from '../utils'

export default function BalanceDebtsSection({ accounts, snapshot }: BalanceProps) {
  const debts = accounts.filter((account) => account.type === 'CREDIT' && (Number(account.balance) || 0) > 0)
  const totals = totalsFromSnapshot(snapshot, 'creditDebtByCurrency')
  if (!debts.length && !totals.UYU && !totals.USD) return <section className="neu-raised rounded-3xl bg-surface/60 p-5 sm:p-6"><div className="flex items-center gap-2.5"><CreditCard className="h-4 w-4 text-muted-foreground" /><h2 className="text-sm font-bold text-foreground">Por pagar</h2></div><p className="mt-2 text-xs text-muted-foreground">No hay deudas de tarjeta registradas.</p></section>
  return <section className="neu-raised rounded-3xl bg-surface p-5 shadow-xs sm:p-6"><header className="mb-3.5 flex items-center gap-2.5 border-b border-border/50 pb-3.5"><CreditCard className="h-4 w-4 text-[#A58D66]" /><div><h2 className="text-sm font-bold text-foreground">Por pagar</h2><p className="text-[11px] text-muted-foreground">Deudas actuales, sin duplicar gastos</p></div></header><div className="divide-y divide-border/40">{debts.map((account) => <div key={account.id} className="flex items-center justify-between gap-3 py-3 first:pt-0"><div className="min-w-0"><p className="truncate text-sm font-semibold text-foreground">{account.name}</p><p className="text-[11px] text-muted-foreground">{accountType(account.type)}{account.dueDay ? ` · Vence el ${account.dueDay}` : ''}{account.closingDay ? ` · Cierre el ${account.closingDay}` : ''}</p></div><p className="shrink-0 text-sm font-bold tabular-nums text-[#A58D66]">{money(Number(account.balance) || 0, account.currency)}</p></div>)}{!debts.length && <div className="flex justify-between py-3 text-sm"><span className="text-muted-foreground">Deuda total registrada</span><span className="font-bold tabular-nums text-[#A58D66]">{totals.UYU ? money(totals.UYU, 'UYU') : money(totals.USD, 'USD')}</span></div>}</div><div className="mt-2 flex items-center gap-1.5 text-[11px] text-muted-foreground"><CalendarClock className="h-3 w-3" />Los pagos se registran como transferencia.</div></section>
}
