'use client'
import { Activity, AlertTriangle, Bot, Check, Clock3, Database, GitBranch, Layers3, Lock, Sparkles, Wrench } from 'lucide-react'
import CustomSelect from '@/components/ui/CustomSelect'
import type { Environment } from '../types'

export const envOptions = [{ value: 'development', label: 'DEV · development' }, { value: 'test', label: 'TEST · staging' }, { value: 'production', label: 'PROD · production' }] as const
export function EnvSelect({ value, onChange }: { value: Environment; onChange: (v: Environment) => void }) { return <CustomSelect value={value} options={envOptions} onChange={v => onChange(v as Environment)} className="w-full sm:w-52 bg-white/10 border-white/20 text-white" /> }
export function AiHeader({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) { return <header className="relative overflow-hidden rounded-[2rem] bg-[#083A4F] px-6 py-8 text-white md:px-10 md:py-10"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-[#407E8C]/30 blur-3xl" /><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-[#C0D5D6]">{eyebrow}</p><h1 className="text-3xl font-semibold tracking-tight md:text-5xl">{title}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#DDE9EB]">{description}</p></div>{children}</div></header> }
export function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`neu-raised rounded-3xl border border-border/50 bg-surface p-5 md:p-6 ${className}`}>{children}</section> }
export function SectionTitle({ icon: Icon, title, note }: { icon: any; title: string; note?: string }) { return <div className="mb-5 flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#DCECEF] text-[#083A4F]"><Icon size={17} /></span><div><h2 className="font-semibold text-[#083A4F]">{title}</h2>{note && <p className="mt-1 text-xs text-[#607078]">{note}</p>}</div></div> }
export function Badge({ children, tone = 'navy' }: { children: React.ReactNode; tone?: 'navy'|'teal'|'gold'|'red'|'green' }) { const colors = { navy: 'bg-[#E2EBEF] text-[#083A4F]', teal: 'bg-[#E2EDF0] text-[#407E8C]', gold: 'bg-[#F6F2EC] text-[#8A7048]', red: 'bg-[#FBE7E7] text-[#B83232]', green: 'bg-[#E6F3EF] text-[#208B6B]' }; return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-bold ${colors[tone]}`}>{children}</span> }
export function Loading({ rows = 4 }: { rows?: number }) { return <div className="animate-pulse space-y-3">{Array.from({ length: rows }).map((_, i) => <div key={i} className="h-12 rounded-2xl bg-[#F0EEEA]" />)}</div> }
export function ErrorState({ error }: { error: string }) { return <div className="flex items-center gap-3 rounded-2xl bg-[#FBE7E7] p-4 text-sm text-[#B83232]"><AlertTriangle size={17} />{error}</div> }
export const icons = { Activity, Bot, Check, Clock3, Database, GitBranch, Layers3, Lock, Sparkles, Wrench }
