'use client'
import { useState } from 'react'
import { Activity, Bot, Clock3, GitBranch, Wrench } from 'lucide-react'
import { useAiConfig, useAiRuns } from '@/features/ai/hooks/useAiAdmin'
import { AiHeader, Badge, Card, EnvSelect, ErrorState, Loading, SectionTitle } from '@/features/ai/components/AiUi'
import type { Environment } from '@/features/ai/types'
export default function AiOverview() { const [env, setEnv] = useState<Environment>('development'); const config = useAiConfig(env); const runs = useAiRuns(); const c: any = config.data || {}; const rows: any[] = Array.isArray(runs.data) ? runs.data : runs.data?.items || []
 return <div className="space-y-6"><AiHeader eyebrow="Finnic / AI control room" title="Calm, capable, under control." description="A clear view of Finnic's behavior, tools and releases. Changes stay private until you decide to publish them."><EnvSelect value={env} onChange={setEnv}/></AiHeader>{config.error && <ErrorState error={config.error}/>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><SectionTitle icon={Bot} title="Finnic status"/><div className="flex items-center gap-2 text-sm font-semibold"><span className="h-2.5 w-2.5 rounded-full bg-[#208B6B]"/> Active</div><p className="mt-3 text-xs text-[#607078]">{c.activePrompt?.key || c.prompt?.key || 'Active configuration loaded'}</p></Card><Card><SectionTitle icon={SparklesIcon} title="Active model"/><p className="text-lg font-semibold text-[#083A4F]">{c.modelConfig?.name || c.model?.name || '—'}</p><p className="mt-2 text-xs text-[#607078]">{c.modelConfig?.provider || 'Production-ready config'}</p></Card><Card><SectionTitle icon={GitBranch} title="Deployment"/><Badge tone="green">{c.deployment?.status || 'healthy'}</Badge><p className="mt-3 text-xs text-[#607078]">{c.deployment?.version || c.activePrompt?.version || 'Current release'}</p></Card><Card><SectionTitle icon={Wrench} title="Tools enabled"/><div className="flex gap-2"><Badge tone="teal">{c.tools?.filter?.((t:any)=>t.enabled && t.risk !== 'write').length || 0} read</Badge><Badge tone="gold">{c.tools?.filter?.((t:any)=>t.enabled && t.risk === 'write').length || 0} write</Badge></div></Card></div><Card><SectionTitle icon={Activity} title="Recent runs" note="Latency and safe error summaries"/>{runs.loading ? <Loading/> : rows.length === 0 ? <p className="py-8 text-center text-sm text-[#607078]">Aún no hay runs registrados.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-[#899399]"><tr><th className="pb-3">Run</th><th>Model</th><th>Latency</th><th>Status</th><th>Error</th></tr></thead><tbody>{rows.slice(0,8).map((r:any,i)=><tr key={r.id||i} className="border-t border-[#EAE7E3]"><td className="py-4 font-medium">{r.id?.slice?.(0,10)||`run-${i+1}`}</td><td>{r.model || '—'}</td><td><span className="inline-flex items-center gap-1"><Clock3 size={13}/>{r.latencyMs || r.latency_ms || '—'} ms</span></td><td><Badge tone={r.error ? 'red' : 'green'}>{r.error ? 'error' : 'success'}</Badge></td><td className="max-w-[220px] truncate text-xs text-[#607078]">{r.error || '—'}</td></tr>)}</tbody></table></div>}</Card></div> }
function SparklesIcon(props: any) { return <span {...props}>✦</span> }
