import type { RankConfig } from './gamification.types'

export const XP_EVENT_LIMITS: Record<string, number> = {
  expense_created: 5,
  expense_with_items: 10,
  receipt_scanned: 10,
  expense_saved_with_items: 5,
  expense_fixed: 15,
  expense_complete_data: 5,
}

export const MAX_XP_PER_EVENT = 500

export const RANKS: RankConfig[] = [
  {
    key: 'refugio_iii',
    name: 'Refugio III',
    tier: 'refugio',
    division: 'III',
    minXp: 0,
    colorLabel: 'stone',
    description: 'Todo viaje empieza con un primer paso.',
  },
  {
    key: 'refugio_ii',
    name: 'Refugio II',
    tier: 'refugio',
    division: 'II',
    minXp: 100,
    colorLabel: 'stone',
    description: 'Estás aprendiendo a registrar tus finanzas.',
  },
  {
    key: 'refugio_i',
    name: 'Refugio I',
    tier: 'refugio',
    division: 'I',
    minXp: 250,
    colorLabel: 'stone',
    description: 'La constancia empieza a dar frutos.',
  },
  {
    key: 'cimiento_iii',
    name: 'Cimiento III',
    tier: 'cimiento',
    division: 'III',
    minXp: 450,
    colorLabel: 'copper',
    description: 'Estás construyendo bases sólidas.',
  },
  {
    key: 'cimiento_ii',
    name: 'Cimiento II',
    tier: 'cimiento',
    division: 'II',
    minXp: 700,
    colorLabel: 'copper',
    description: 'Tus hábitos financieros se fortalecen.',
  },
  {
    key: 'cimiento_i',
    name: 'Cimiento I',
    tier: 'cimiento',
    division: 'I',
    minXp: 1000,
    colorLabel: 'copper',
    description: 'Ya tenés un cimiento financiero firme.',
  },
  {
    key: 'muralla_iii',
    name: 'Muralla III',
    tier: 'muralla',
    division: 'III',
    minXp: 1400,
    colorLabel: 'bronze',
    description: 'Protección y orden en tus finanzas.',
  },
  {
    key: 'muralla_ii',
    name: 'Muralla II',
    tier: 'muralla',
    division: 'II',
    minXp: 1850,
    colorLabel: 'bronze',
    description: 'Tus defensas financieras crecen.',
  },
  {
    key: 'muralla_i',
    name: 'Muralla I',
    tier: 'muralla',
    division: 'I',
    minXp: 2350,
    colorLabel: 'bronze',
    description: 'Una muralla de buenos hábitos te respalda.',
  },
  {
    key: 'torre_iii',
    name: 'Torre III',
    tier: 'torre',
    division: 'III',
    minXp: 2950,
    colorLabel: 'silver',
    description: 'Tu visión financiera se eleva.',
  },
  {
    key: 'torre_ii',
    name: 'Torre II',
    tier: 'torre',
    division: 'II',
    minXp: 3650,
    colorLabel: 'silver',
    description: 'Alcanzás perspectiva desde las alturas.',
  },
  {
    key: 'torre_i',
    name: 'Torre I',
    tier: 'torre',
    division: 'I',
    minXp: 4450,
    colorLabel: 'silver',
    description: 'Torre firme, mirada clara.',
  },
  {
    key: 'bastion_iii',
    name: 'Bastión III',
    tier: 'bastion',
    division: 'III',
    minXp: 5400,
    colorLabel: 'gold',
    description: 'El brillo del control financiero.',
  },
  {
    key: 'bastion_ii',
    name: 'Bastión II',
    tier: 'bastion',
    division: 'II',
    minXp: 6500,
    colorLabel: 'gold',
    description: 'Tus finanzas tienen resplandor propio.',
  },
  {
    key: 'bastion_i',
    name: 'Bastión I',
    tier: 'bastion',
    division: 'I',
    minXp: 7750,
    colorLabel: 'gold',
    description: 'Bastión dorado de la responsabilidad.',
  },
  {
    key: 'fortaleza_iii',
    name: 'Fortaleza III',
    tier: 'fortaleza',
    division: 'III',
    minXp: 9200,
    colorLabel: 'emerald',
    description: 'Fortaleza verde de crecimiento.',
  },
  {
    key: 'fortaleza_ii',
    name: 'Fortaleza II',
    tier: 'fortaleza',
    division: 'II',
    minXp: 10850,
    colorLabel: 'emerald',
    description: 'Control financiero sólido.',
  },
  {
    key: 'fortaleza_i',
    name: 'Fortaleza I',
    tier: 'fortaleza',
    division: 'I',
    minXp: 12700,
    colorLabel: 'emerald',
    description: 'Fortaleza inquebrantable.',
  },
  {
    key: 'ciudadela_iii',
    name: 'Ciudadela III',
    tier: 'ciudadela',
    division: 'III',
    minXp: 14800,
    colorLabel: 'sapphire',
    description: 'Tu reino financiero se expande.',
  },
  {
    key: 'ciudadela_ii',
    name: 'Ciudadela II',
    tier: 'ciudadela',
    division: 'II',
    minXp: 17200,
    colorLabel: 'sapphire',
    description: 'Sabiduría y orden en cada gasto.',
  },
  {
    key: 'ciudadela_i',
    name: 'Ciudadela I',
    tier: 'ciudadela',
    division: 'I',
    minXp: 19900,
    colorLabel: 'sapphire',
    description: 'Ciudadela de hábitos ejemplares.',
  },
  {
    key: 'santuario_iii',
    name: 'Santuario III',
    tier: 'santuario',
    division: 'III',
    minXp: 23000,
    colorLabel: 'violet',
    description: 'Santuario de la disciplina.',
  },
  {
    key: 'santuario_ii',
    name: 'Santuario II',
    tier: 'santuario',
    division: 'II',
    minXp: 26500,
    colorLabel: 'violet',
    description: 'Tu conexión financiera se profundiza.',
  },
  {
    key: 'santuario_i',
    name: 'Santuario I',
    tier: 'santuario',
    division: 'I',
    minXp: 30500,
    colorLabel: 'violet',
    description: 'Santuario de la abundancia consciente.',
  },
  {
    key: 'custodio',
    name: 'Custodio',
    tier: 'custodio',
    division: null,
    minXp: 35000,
    colorLabel: 'pearl',
    description: 'Guardian de tus finanzas.',
  },
  {
    key: 'centinela',
    name: 'Centinela',
    tier: 'centinela',
    division: null,
    minXp: 40500,
    colorLabel: 'ruby',
    description: 'Vigilante incansable del orden.',
  },
  {
    key: 'regente',
    name: 'Regente',
    tier: 'regente',
    division: null,
    minXp: 47000,
    colorLabel: 'imperial',
    description: 'Gobernás tus finanzas con maestría.',
  },
  {
    key: 'lovehold',
    name: 'Lovehold',
    tier: 'lovehold',
    division: null,
    minXp: 55000,
    colorLabel: 'prism',
    description: 'La cima del control financiero en pareja.',
  },
]
